### ISSUE TITLE
Server fails to start on windows

### ISSUE THREAD

**Issue by lhjt** [StarToLeft/snowflake-rs#1]
The server fails to start on Windows when the port is set to `50051`.

The error is:
```
{ code: 10013, kind: PermissionDenied, message: "An attempt was made to access a socket in a way forbidden by its access permissions." }
```

I think that the port `50051` is too high, and suggest lowering the port number to something like `10001`, which allows windows users to run the server. If you don't plan on supporting windows, then I don't think there's any need for any changes.

There is no issue on linux.

**Comment by StarToLeft** [comment]
Will implement support for windows through an environment variable and set the default port to 10001.
